server:
  port: 8090
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: micro1
        uri: http://localhost:8022
        predicates:
          - Path=/product/**
        filters:
          - StripPrefix=1
      - id: micro2
        uri: http://localhost:8023
        predicates:
          - Path=/transaction/**
        filters:
          - StripPrefix=1
      - id: micro3
        uri: http://localhost:8093
        predicates:
          - Path=/consults/**
        filters:
          - StripPrefix=1